config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  resources :books
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:created]="Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index

    end
  end
  def index
    @books = Book.all
    @book = Book.new
  end
  def show
     @book = Book.find(params[:id])
  end

  def edit
     @book = Book.find(params[:id])

  end
   def update
     @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:created]="Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :edit
    end

   end

  def destroy
     @book = Book.find(params[:id])
     @book.destroy
    redirect_to '/books'
  end

  private

   def book_params
    params.require(:book).permit(:title, :body)
   end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new  
  end
   def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list.id)
    else
      render :new 
    end

  def index
    @lists = List.all  
  end

  def show
     @list = List.find(params[:id])  
  end

  def edit
     @list = List.find(params[:id])
  end
   def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to list_path(list.id)  
   end
  
  private
  
   def list_params
    params.require(:list).permit(:title, :body)
   end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

  <%= f.label :Title %><br>
  <%= f.text_field :title %><br>
  <br>
  <%= f.label :Body %><br>
  <%= f.text_area :body %><br>
  <br>
  <%= f.submit 'Update Book' %>
  <br>
 <% end %>
  <br>
  <%= link_to "Show", book_path(@book.id) %>
  |
  <%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
<% @books.each do |book| %>


      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', book_path(book.id) %></td>
        <td><%= link_to 'Edit', edit_book_path(book.id) %></td>
        <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
      </tr>
<% end %>
  </tbody>
</table>
<h2>New book</h2>

<div id="error-explanation"></div>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>
<%= form_with model: @book, url: '/books', method: :post do |f| %>
  <%= f.label :Title %><br>
  <%= f.text_field :title %><br>
  <br>
  <%= f.label :Body %><br>
  <%= f.text_area :body %>
  <br>
  <br><%= f.submit 'Create Book' %><br>
<% end %>

<p style="color: green;"><%=flash[:created]%> </p>

app/views/books/new.html.erb
<h1>新規投稿</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>  
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: '/book', method: :post do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<p style="color: green;"><%=flash[:alert]%> </p>
<p style="color: green;"><%=flash[:created]%> </p>
<p><strong>Title:</strong>
<%=@book.title %><p/>
<p><strong>Title:</strong>
<%=@book.body %></p>
<%= link_to "Edit", edit_book_path(@book.id) %>
|
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p><a href="/books">start</a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>